version: '3.8'

services:
  legacy_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: legacy_user
      POSTGRES_PASSWORD: legacy_password
      POSTGRES_DB: legacy_database
    ports:
      - "5433:5432" # Mapping to 5433 so it doesn't conflict with target

  modern_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: modern_user
      POSTGRES_PASSWORD: modern_password
      POSTGRES_DB: modern_database
    ports:
      - "5434:5432"
